### ISSUE TITLE
现在创建任务的之后，同一个类型的素材好像不支持不同任务不同优先级，会导致 Low 的任务被 cancel 并且 Normal 的任务也不被执行

### ISSUE THREAD

**Issue by web3nomad** [bmrlab/gendam#101]
https://github.com/bmrlab/gendam/blob/8a9212eb922aedd40999be107c66f9d716e5a436/crates/content-base/src/core.rs#L43

https://github.com/bmrlab/gendam/blob/8a9212eb922aedd40999be107c66f9d716e5a436/crates/content-base-pool/src/pool.rs#L178-L179
逻辑应该在这段代码

**Comment by zhuojg** [comment]
看起来跟这里一样

https://github.com/bmrlab/gendam/issues/109#issuecomment-2482405037
