### ISSUE TITLE
有时候会遇到没有正在执行的任务而且也不继续执行新的任务

### ISSUE THREAD

**Issue by web3nomad** [bmrlab/gendam#109]
有可能是因为什么原因，这里没有把 `add_permits`

https://github.com/bmrlab/gendam/blob/bf494dd06d40f958202506f4e12f48a5fd17c533/crates/content-base-pool/src/pool.rs#L518-L519

复现场景
- app 启动的时候，批量开始一堆任务，偶尔会卡住
- 一次新上传大量文件或者通过 rebuild index 菜单触发大量任务，偶尔也会卡住
- 这里有个相关的 bug 也可能是一样的原因 https://github.com/bmrlab/gendam/issues/103#issuecomment-2480809338

目前还没法定位问题，一个假设是始终拿不到 semaphore 的 permit，所以先这么处理 

- [x] `add_permits` 加个日志，方便遇到问题的时候确认这里是否已经执行
- [x] `loop_for_task_execution` 每隔一段时间输出日志，确保循环还在，只是拿不到 permit
- [ ] 死锁不好定位，找一个插件在编译阶段判断死锁可能性

**Comment by zhuojg** [comment]
看起来是因为在 TaskPool 里处理任务优先级的时候，两次执行了 `task_ctx.task_queue.write().await` 造成了死锁

```rust
{
    let mut task_queue = task_ctx.task_queue.write().await; // 👈 第一次
    task_queue.push(task_id, priority);

    // 处理任务优先级
    let current_priority = priority;
    if task_ctx.semaphore.available_permits() == 0 {
        // 找到优先级低于当前任务的任务，并取消它
        let task_priority = task_ctx.task_priority.write().await;
        let mut min_task_id: Option<TaskId> = None;
        for (task_id, priority) in task_priority.iter() {
            if priority < &current_priority {
                if let Some(_min_task_id) = &min_task_id {
                    if priority < &task_priority[_min_task_id] {
                        min_task_id = Some(task_id.clone());
                    }
                } else {
                    min_task_id = Some(task_id.clone());
                }
            }
        }

        if let Some(task_id) = &min_task_id {
            let mut task_mapping = task_ctx.task_mapping.write().await;
            if let Some(item) =
                task_mapping.get_mut(&task_id.to_store_key())
            {
                item.cancel().await;

                // 需要把任务重新添加回去
                let mut task_queue = task_ctx.task_queue.write().await; // 👈 第二次
                task_queue.push(task_id.clone(), item.priority.clone());
            }
        }
    }
}
```

**Comment by web3nomad** [comment]
死锁解决了，https://github.com/bmrlab/gendam/commit/a1c714fe5900fc558d8ba11d12644b31935eefbe

- [ ] 死锁不好定位，找一个插件在编译阶段判断死锁可能性

留下一个新问题，被取消的任务重新执行的时候，会遇到 pop_next_task 方法里抛出的 task not found 错误，

walkthrough 是这样

1. 低优先级 task A 开始执行，async 闭包开启
2. 高优先级 task B 放进队列，
3. 找到 task A，触发取消，队列开始执行下一个任务，也就是 task B

4. 之前 task A 已开启的 async 闭包执行结束，调用 task_mapping.remove(&task_id...
https://github.com/bmrlab/gendam/blob/a1c714fe5900fc558d8ba11d12644b31935eefbe/crates/content-base-pool/src/pool.rs#L544-L547

5. task B 执行结束开始，队列开始下一个任务 task A，但是 task A pop 出来的时候 task_mapping 里面已经没有 A 的信息了。
https://github.com/bmrlab/gendam/blob/a1c714fe5900fc558d8ba11d12644b31935eefbe/crates/content-base-pool/src/pool.rs#L368-L375

**Comment by web3nomad** [comment]
> 死锁解决了，[a1c714f](https://github.com/bmrlab/gendam/commit/a1c714fe5900fc558d8ba11d12644b31935eefbe)
> 
> * [ ]  死锁不好定位，找一个插件在编译阶段判断死锁可能性
> 
> 留下一个新问题，被取消的任务重新执行的时候，会遇到 pop_next_task 方法里抛出的 task not found 错误，
> 
> walkthrough 是这样
> 
> 1. 低优先级 task A 开始执行，async 闭包开启
> 2. 高优先级 task B 放进队列，
> 3. 发送取消 task A 的信号，任务取消，队列开始执行下一个任务，也就是 task B
>    https://github.com/bmrlab/gendam/blob/a1c714fe5900fc558d8ba11d12644b31935eefbe/crates/content-base-pool/src/pool.rs#L522-L523
> 4. 之前 task A 已开启的 async 闭包因为 cancel 信号收到，继续执行，不再等待 `current_task.task.task_type.run` 的完成，调用 task_mapping.remove(&task_id...
>    https://github.com/bmrlab/gendam/blob/a1c714fe5900fc558d8ba11d12644b31935eefbe/crates/content-base-pool/src/pool.rs#L544-L547
> 5. task B 执行结束开始，队列开始下一个任务 task A，但是 task A pop 出来的时候 task_mapping 里面已经没有 A 的信息了。
>    https://github.com/bmrlab/gendam/blob/a1c714fe5900fc558d8ba11d12644b31935eefbe/crates/content-base-pool/src/pool.rs#L368-L375

解决方案是 cancel 的时候保留 task_mapping，

**不过要注意：**
不能同时保留 task_priority 的信息，因为高优先级的任务每次会从 task_priority 里寻找一个比自己优先级低的任务，简单保留会让一个低优先级的任务多次被不同的高优先级任务找到并取消，这样它就会收到多个 cancel 信号，导致重新丢入队列以后一直没机会执行完成。

由于 task_priority 是在 async_exec_task 里面开始执行任务之前插入的，所以确实可以不保留，而且被取消的任务重新加入队列的时候也不需要插入 task_priority

**Comment by web3nomad** [comment]
另一个注意点，

cancel_token 只要被 cancel 过，这里的 `tokio::select!` 其实就一直会跳到 
`_ = current_task.priority_cancel_token.cancelled() => {` 块里了。

cancel_token 不能复用，他应该就是用 channel 实现的，所以被取消还要重新执行的任务需要一个全新的 cancel token。

实现方式就是创建个全新的 `TaskInQueue` 副本，时机是 `task_mapping.remove` 旧的 `TaskInQueue` 以后立即创建一个全新的 `TaskInQueue` 并 `task_mapping.set`，而不是在 `task_mapping` 中一直保留原来的 `TaskInQueue` 对象。
