### ISSUE TITLE
优化 library 切换，退出旧 library -> 加载新 library -> 重启 tasks

### ISSUE THREAD

**Issue by web3nomad** [bmrlab/gendam#51]
有个可以优化的是：任务重试支持从第一个没成功的任务开始，也就是两种 mode，一种是 startover 另一种是 continue

**Comment by zhuojg** [comment]
逻辑已经实现了，有几个编码的小问题：
- 现在把逻辑实现在了ctx上，方便在应用启动 load_library 之后发起一个异步的 task 进行触发
- 在 switch_current_library 的时候就不太这么触发，会阻塞用户操作（虽然也很快），因此切换 library 的触发逻辑写在前端了

**Comment by web3nomad** [comment]
> 逻辑已经实现了，有几个编码的小问题：
> 
> * 现在把逻辑实现在了ctx上，方便在应用启动 load_library 之后发起一个异步的 task 进行触发
> * 在 switch_current_library 的时候就不太这么触发，会阻塞用户操作（虽然也很快），因此切换 library 的触发逻辑写在前端了

确实，放在前端是更好的。
switch library 和启动 app 以后都靠前端来触发。

**Comment by zhuojg** [comment]
先把 ctx 上的 switch_current_library 做了一下拆分，分为了 quit_current_library 和 load_library

应用启动和切换 library 的时候，都在前端先 quit 再 load

这样的话，就可以把后端 load_library 等逻辑都去掉了，这个明天我改一下看看

**Comment by web3nomad** [comment]
@zhuojg 前端我改掉了 https://github.com/bmrlab/tauri-dam-test-playground/commit/dc0fc3d7775fe85840528496c9cc9e92cbe7e19f

> 这样的话，就可以把后端 load_library 等逻辑都去掉了，这个明天我改一下看看

然后 👆 这里说的是后端改一下 👇 这部分对吧

https://github.com/bmrlab/tauri-dam-test-playground/blob/dc0fc3d7775fe85840528496c9cc9e92cbe7e19f/apps/api-server/src/routes/libraries/mod.rs#L81

这个我还没改，你来改改？

**Comment by zhuojg** [comment]
我在 7091483bc40fe1241191234b964f3cbc888e2261 整体改动了一下：
- ctx 里只剩下 `load_library` 和 `quit_library_in_store`
  - `load_library`: 根据 id 加载 library, 在 `load_library` 时会先进行 quit 的操作
  - `quit_library_in_store`: 根据 store 中的信息卸载某个 library
- 接口
  - `set_current_library` - 执行 `ctx.load_library`
  - `quit_current_library` - `ctx.quit_library_in_store`
  - `get_current_library` - 返回 `ctx.library()`, 如果失败则先用 store 中的 id 调用 `ctx.load_library`，再返回
- 前端调用逻辑
  - 初始化：调用 `get_current_library`
  - 切换 library：调用 `set_current_library`
  - 退出：调用 `quit_current_library`

**Comment by web3nomad** [comment]
我周末这里调整了一下，先是 ctx 上分成了 load_library 和 unload_library 两个方法，也对应 2 个接口：

load_library 的顺序是
1. init library (push db, start qdrant server)
2. update library in ctx and in store
3. check qdrant
4. init task pool
5. init download hub
6. init ai handler
7. trigger unfinished tasks

unload_library 的顺序是
1. cancel tasks
2. unload qdrant
3. shutdown ai handler
4. remove library from ctx and from store

然后
- load_library 方法里不会做任何 unload 相关的操作，load_library 只会在 ctx.library 为空的时候执行
- **load_library 和 unload_library 在 rspc 请求中放在一个线程里执行**，这样请求被 cancel 的时候（比如页面刷新）这两个方法还会继续执行，之前一些意想不到的问题很多都是和请求取消以后导致 load 和 unload 过程中断导致。
- load_library 和 unload_library 通过一个叫 is_busy (代替之前的 loading_library) 的锁来确保串行，这个锁通过 drop trait 在方法结束以后自动释放。
- 确保串行以后，这两个方法都可以重复执行，
  - unload 每次执行都会跑一遍所有流程
  - load 对同一个 library 会直接跳过，对不同的 library 会提示错误
- 这样前端每次调用过程是 
  - 切换 library 的时候: unload_library -> load_library(id)
  - 启动 app
    - 选择了 library_id 的时候: load_library(id)
    - 没选择 library 的时候: 选择一个 library 然后 unload_library -> load_library(id)
  - 切换页面: load_library(id)
  - 退出 app
    - unload_library 以后 process.exit(0)


https://github.com/bmrlab/gendam/commit/2880a03578d8b1562958f6f908966e36dd57cf72 ... https://github.com/bmrlab/gendam/commit/a3b5b62e73cccb81a9deb04721d378e2b44a2e2c

先 close 了
