### ISSUE TITLE
上线前的一系列 UI 补全

### ISSUE THREAD

**Issue by web3nomad** [bmrlab/gendam#52]
上线前的一系列 UI 补全

- [x] 左侧文件夹树
- [x] 设置 library 页面
- [x] squash migrations #53
- [x] 统一多种类型的 toast，优化提醒文案
- [x] 语言全部改成英文
- [x] 空白页面的插画
- [x] 对 search 结果进行 group
- [x] 搜索结果点击以后跳转到对应的素材库页面
- [x] settings 要存下来：dark/light，layout，etc.
- [x] 切换 library 要 loading (可以直接进去首页)
- [x] 文件上传失败重试 #6
- [x] muse-v2 xxx 这个名字都改掉
- [x] 上传队列的显示按钮收到左侧 sidebar，不要在右下角一直显示
- [x] 登录以后可以使用，个人中心页面支持登出
- [x] 反馈窗口

**Comment by web3nomad** [comment]
关注的 issue, 多测试

- [ ] #51
- [ ] #48 
- [ ] #20
- [ ] #24

**Comment by zhuojg** [comment]
<img width="1141" alt="image" src="https://github.com/bmrlab/tauri-dam-test-playground/assets/24386525/4334d57b-9c9f-4858-921c-dfb5aca6ca8d">

- [ ] 邮件菜单和 more action 保持一致

这里菜单是不是应该保持一致，我来改一下

**Comment by zhuojg** [comment]
> <img alt="image" width="1141" src="https://private-user-images.githubusercontent.com/24386525/322423841-4334d57b-9c9f-4858-921c-dfb5aca6ca8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNzkxNjUsIm5iZiI6MTcxMzE3ODg2NSwicGF0aCI6Ii8yNDM4NjUyNS8zMjI0MjM4NDEtNDMzNGQ1N2ItOWM5Zi00ODU4LTkyMWMtZGZiNWFjYTZjYThkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDExMDEwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxMWE0MmRjYWRmMzM2MjA1NWJmY2JhZTk0MDAwNjZmMTUzYjFiZmExMjY0Yzk5Y2NlNjNkY2E1NmM5YTUxOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gOok9jVnDQL7KZHunbBThQa0oZjZIqqlv83mdZcDYEE">
> * [ ]  右键菜单和 more action 保持一致
> 
> 这里菜单是不是应该保持一致，我来改一下

fixed in b04db1d087709da3238a1ff3fceabe17bf06d1ad

**Comment by web3nomad** [comment]
> > <img alt="image" width="1141" src="https://private-user-images.githubusercontent.com/24386525/322423841-4334d57b-9c9f-4858-921c-dfb5aca6ca8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNzkxNjUsIm5iZiI6MTcxMzE3ODg2NSwicGF0aCI6Ii8yNDM4NjUyNS8zMjI0MjM4NDEtNDMzNGQ1N2ItOWM5Zi00ODU4LTkyMWMtZGZiNWFjYTZjYThkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDExMDEwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxMWE0MmRjYWRmMzM2MjA1NWJmY2JhZTk0MDAwNjZmMTUzYjFiZmExMjY0Yzk5Y2NlNjNkY2E1NmM5YTUxOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gOok9jVnDQL7KZHunbBThQa0oZjZIqqlv83mdZcDYEE">
> > * [ ]  右键菜单和 more action 保持一致
> > 这里菜单是不是应该保持一致，我来改一下
> 
> fixed in [b04db1d](https://github.com/bmrlab/tauri-dam-test-playground/commit/b04db1d087709da3238a1ff3fceabe17bf06d1ad)

这里有个差别，singleExport 可以预览 transcript，这里有个 isBatchSelected 的判断我加回去了。
