### ISSUE TITLE
文件夹有关的功能增强

### ISSUE THREAD

**Issue by ginkoten** [bmrlab/gendam#57]
- [x] 把 “Folders” 直接作为根目录，下面默认不需要有“home”这个文件夹
- [x] "Folders"旁边加一个“+”，可快速创建新文件夹
- [x] 上传支持选择一个文件夹
- [x] 左侧文件夹树可以删除文件夹

**Comment by web3nomad** [comment]
上传支持选择一个文件夹 🎉
https://github.com/bmrlab/gendam/commit/e39523254e0e256c746697eefe849108d26cc182
