### ISSUE TITLE
embedding 的字符串如果是空，一般是 rawtext 或 transcription 的 sum 结果为空 (比如 qwen 推理出错)，就很容易匹配到搜索词，在返回结果里排名较高。

### ISSUE THREAD

**Issue by web3nomad** [bmrlab/gendam#90]
- [x] trans-sum 和 image-description 任务如果调用 llm 服务出错，应停止任务，并且状态是 error (https://github.com/bmrlab/gendam/commit/eacea48a79be8120246abf36dcaca588b8343db7)

https://github.com/bmrlab/gendam/issues/90#issuecomment-2373549807 提到的“过滤空字符串”可以暂时不处理，只要 llm 服务出错后不写入空字符串，其他情况不大会出现空字符串

**Comment by zhuojg** [comment]
- [ ] 可以在生成 embedding 的时候，过滤空字符串的情况 @zhuojg 
- [ ] 引入全文搜索后，结合一下全文搜索的分数，避免这种情况发生

**Comment by web3nomad** [comment]
xxx-sum 任务如果出错，可以停止任务，
字符串如果是空 xxx-embed 任务的状态其实也可以是出错，
最终，这个素材的状态就是 “not search ready” 的。

上面两点一方面是方便排查，二是task的成功失败的定义更直观（对无效的payload进行embedding的时候，是一种“输入错误”）。

**Comment by web3nomad** [comment]
> xxx-sum 任务如果调用 llm 服务出错，可以停止任务，并且状态是 error 输入字符串如果是空， xxx-embed 任务的状态其实也可以是 error， 最终，这个素材的状态就是 “not search ready” 的。
> 
> 上面两点一方面是方便排查，二是task的成功失败的定义更直观（对无效的payload进行embedding的时候，是一种“输入错误”）。

~输入字符串如果是空， xxx-embed 任务的状态其实也可以是 error，~
这里我说错了，不应该是 error，应该特殊处理下，直接就不生成 embedding。
空字符串等等不应该是一种错误输入，而是要优化 embedding 模型本身。
